services:
  - type: web
    name: safar
    runtime: python
    buildCommand: bash ./render_build.sh
    startCommand: gunicorn --worker-class gthread --threads 100 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: postgresql+pg8000://postgres:AI_Defenders_2026@db.cicxpxpssoqetgvheqcg.supabase.co:5432/postgres?sslmode=require
      - key: SECRET_KEY
        value: change_me_in_production
      - key: SUPABASE_URL
        value: https://cicxpxpssoqetgvheqcg.supabase.co
      - key: SUPABASE_KEY
        value: sb_publishable_nPdidfXwWche0uZhinIxNg_Ag2-mjok
